//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplyDetail
    {
        public int ApplyDetailNumber { get; set; }
        public int ApplyNumber { get; set; }
        public Nullable<int> CostCategory { get; set; }
        public Nullable<decimal> Amont { get; set; }
    
        public virtual Travel_Expense_Application Travel_Expense_Application { get; set; }
    }
}
