//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Found
    {
        public int FoundID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> Deparment { get; set; }
        public string Phone { get; set; }
        public string FoundSubject { get; set; }
        public string FoundCategory { get; set; }
        public byte[] FoundPropertyPhoto { get; set; }
        public string FoundProperty { get; set; }
        public Nullable<System.DateTime> FoundDate { get; set; }
        public string FoundSpace { get; set; }
        public string FoundPropertyDescription { get; set; }
        public Nullable<byte> FoundCheckStatus { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual FoundPropertyCheckStatu FoundPropertyCheckStatu { get; set; }
        public virtual User User { get; set; }
    }
}
