//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyHREntities : DbContext
    {
        public MyHREntities()
            : base("name=MyHREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Absence> Absences { get; set; }
        public virtual DbSet<Bulletin> Bulletins { get; set; }
        public virtual DbSet<CheckStatu> CheckStatus { get; set; }
        public virtual DbSet<CostCategory> CostCategories { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Found> Founds { get; set; }
        public virtual DbSet<FoundPropertyCheckStatu> FoundPropertyCheckStatus { get; set; }
        public virtual DbSet<InterViewee> InterViewees { get; set; }
        public virtual DbSet<InterViewStatu> InterViewStatus { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<JobTitle> JobTitles { get; set; }
        public virtual DbSet<Leave> Leaves { get; set; }
        public virtual DbSet<LeaveApplication> LeaveApplications { get; set; }
        public virtual DbSet<Lost> Losts { get; set; }
        public virtual DbSet<LostPropertyCheckStatu> LostPropertyCheckStatus { get; set; }
        public virtual DbSet<OnBoardStatu> OnBoardStatus { get; set; }
        public virtual DbSet<Repair> Repairs { get; set; }
        public virtual DbSet<Store> Stores { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Travel_Expense_Application> Travel_Expense_Application { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<WuChaOrder> WuChaOrders { get; set; }
        public virtual DbSet<ApplyDetail> ApplyDetails { get; set; }
        public virtual DbSet<OrderStoreDetail> OrderStoreDetails { get; set; }
    }
}
