//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class InterViewee
    {
        public int InterVieweeID { get; set; }
        public string InterVieweeGender { get; set; }
        public string InterVieweeName { get; set; }
        public string EmployeeEnglishName { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public Nullable<int> Age { get; set; }
        public byte[] Photo { get; set; }
        public string Education { get; set; }
        public string Experience { get; set; }
        public Nullable<int> JobTitle { get; set; }
        public Nullable<int> Department { get; set; }
        public Nullable<int> InterViewerEmployeeID { get; set; }
        public Nullable<System.DateTime> InterViewDate { get; set; }
        public Nullable<int> InterViewStatus { get; set; }
        public string InterViewProcessID { get; set; }
    
        public virtual Department Department1 { get; set; }
        public virtual InterViewStatu InterViewStatu { get; set; }
        public virtual JobTitle JobTitle1 { get; set; }
        public virtual User User { get; set; }
    }
}
