//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Travel_Expense_Application
    {
        public int ApplyNumber { get; set; }
        public int EmployeeID { get; set; }
        public string Reason { get; set; }
        public System.DateTime ApplyDate { get; set; }
        public System.DateTime TravelStartTime { get; set; }
        public System.DateTime TravelEndTime { get; set; }
        public decimal Amont { get; set; }
        public int CheckStatus { get; set; }
    
        public virtual CheckStatu CheckStatu { get; set; }
        public virtual ApplyDetail ApplyDetail { get; set; }
        public virtual User User { get; set; }
    }
}
