//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class WuChaOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WuChaOrder()
        {
            this.OrderStoreDetails = new HashSet<OrderStoreDetail>();
        }
    
        public int WuChaOrderNumber { get; set; }
        public string GroupID { get; set; }
        public int StoreID { get; set; }
        public int EmployeeID { get; set; }
        public System.DateTime Date { get; set; }
        public int TotalPirce { get; set; }
    
        public virtual Store Store { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderStoreDetail> OrderStoreDetails { get; set; }
    }
}
